# Mulilabel and Multioutput classification

## Setup

In [1]:
import os
if os.getcwd().endswith("notebooks"):
    os.chdir('..')

print("Current working directory: ", os.getcwd())
if not os.getcwd().endswith("Classifying-the-MNIST"):
    raise ValueError("Please change working directory to 'path/Classifying-the-MNIST' before proceeding")

Current working directory:  /Users/irellzane/MLprojects/Classifying-the-MNIST


In [2]:
!pip install -r requirements.txt

In [6]:
import numpy as np
import pandas as pd

from sklearn.datasets import fetch_openml

mnist = fetch_openml("mnist_784", as_frame=False)

In [7]:
X_train, X_test = mnist.data[:6000], mnist.data[6000:]
y_train, y_test = mnist.target[:6000], mnist.target[6000:]

## Multilabel Classification

In [44]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import f1_score
from sklearn.dummy import DummyClassifier

In [45]:
y_train_large = (y_train >= '7')
y_train_odd = (y_train.astype('int8') % 2 == 1)
y_train_prime = np.isin(y_train.astype('int8'), [2, 3, 5, 7])
y_multilabel = np.c_[y_train_large, y_train_odd, y_train_prime]
y_multilabel

array([[False,  True,  True],
       [False, False, False],
       [False, False, False],
       ...,
       [ True, False, False],
       [False, False, False],
       [ True,  True, False]])

In [46]:
knn_clf = KNeighborsClassifier()
dummy_clf = DummyClassifier()
knn_clf.fit(X_train, y_multilabel)

KNeighborsClassifier()

In [47]:
some_digit = X_train[0]

print(y_train[0])
knn_clf.predict([some_digit])

5


array([[False,  True,  True]])

In [51]:
y_train_knn_pred = cross_val_predict(knn_clf, X_train, y_multilabel, cv=3)
y_train_dummy_pred = cross_val_predict(dummy_clf, X_train, y_multilabel, cv=3)

array([[False,  True, False],
       [False,  True, False],
       [False,  True, False],
       ...,
       [False,  True, False],
       [False,  True, False],
       [False,  True, False]])

In [50]:
print(f1_score(y_multilabel, y_train_knn_pred, average="macro"))
print(f1_score(y_train, y_train_dummy_pred, average="macro"))

0.95097845146962


ValueError: Classification metrics can't handle a mix of multiclass and multilabel-indicator targets